import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import {GLTFLoader} from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/loaders/GLTFLoader.js';

const $=s=>document.querySelector(s), clamp=(v,a=0,b=1)=>Math.min(b,Math.max(a,v)), lerp=(a,b,t)=>a+(b-a)*t;
const smoothstep=(a,b,x)=>{const t=clamp((x-a)/(b-a));return t*t*(3-2*t)}, rangeProgress=(p,a,b)=>clamp((p-a)/(b-a)), segmentInOut=(p,a,b,inT=.18,outT=.18)=>[smoothstep(a,a+(b-a)*inT,p),1-smoothstep(b-(b-a)*outT,b,p)];
const timeline={intro:[.03,.18],split:[.15,.25],storyA:[.25,.44],panorama:[.44,.48],storyB:[.48,.74],catalog:[.75,.96],settle:[.91,1]};
const state={target:0,playhead:0,pointerX:0,pointerY:0,px:0,py:0,raf:0,dirty:true,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches};
const section=$('.cinematic-scroll'), stage=$('.cinematic-stage'), root=$('#three-root'), loading=$('#loading');
let renderer,scene,camera,bottle,clock=new THREE.Clock();
function setup3D(){scene=new THREE.Scene(); camera=new THREE.PerspectiveCamera(28,innerWidth/innerHeight,.1,100);camera.position.set(0,.15,6.7);
 renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;root.appendChild(renderer.domElement);
 const hemi=new THREE.HemisphereLight(0xeee1cc,0x100d0a,1.4);scene.add(hemi); const key=new THREE.DirectionalLight(0xffe2b2,4.5);key.position.set(3,5,4);scene.add(key);const rim=new THREE.DirectionalLight(0x9e805d,3);rim.position.set(-4,2,-2);scene.add(rim);
 const loader=new GLTFLoader();loader.load('./assets/perfume_bottle.glb',g=>{bottle=g.scene; bottle.traverse(o=>{if(o.isMesh){o.castShadow=false;o.receiveShadow=false;o.frustumCulled=true}});const box=new THREE.Box3().setFromObject(bottle),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());const s=2.35/Math.max(size.x,size.y,size.z);bottle.scale.setScalar(s);bottle.position.sub(center.multiplyScalar(s));bottle.position.y=-.15;scene.add(bottle);loading.classList.add('done');state.dirty=true},undefined,()=>{loading.querySelector('p').textContent='THE NIGHT IS READY';setTimeout(()=>loading.classList.add('done'),500)});}
function setScrollTarget(){const r=section.getBoundingClientRect(), max=Math.max(1,section.offsetHeight-innerHeight);state.target=clamp((-r.top)/max);requestFrame()}
function renderScene(p){const intro=rangeProgress(p,...timeline.intro), split=rangeProgress(p,...timeline.split), a=rangeProgress(p,...timeline.storyA), b=rangeProgress(p,...timeline.storyB), cat=rangeProgress(p,...timeline.catalog);
 document.documentElement.style.setProperty('--p',p);$('.intro').style.opacity=1-smoothstep(.03,.18,p);$('.intro').style.transform=`translate3d(${state.px*.25}px,calc(-50% + ${-smoothstep(.03,.18,p)*8}px),0)`;
 $('.narrative-a').style.opacity=segmentInOut(p,.25,.44,.22,.25).join('');
 $('.narrative-b').style.opacity=segmentInOut(p,.48,.74,.2,.2).join('');
 $('.catalog').style.opacity=smoothstep(.75,.84,p);$('.catalog').style.transform=`translate3d(${lerp(90,0,smoothstep(.75,.9,p))}px,0,0)`;
 $('.portal-left').style.transform=`translate3d(${-smoothstep(.15,.44,p)*115}%,0,0)`;$('.portal-right').style.transform=`translate3d(${smoothstep(.15,.44,p)*115}%,0,0)`;
 $('.shade').style.opacity=.25+.18*(a*(1-a))+(.18*(b*(1-b)));
 if(bottle){const focus=smoothstep(.18,.35,p), retreat=smoothstep(.69,.76,p);bottle.rotation.y=p*Math.PI*1.25+state.px*.035;bottle.rotation.x=state.py*.025;bottle.position.x=lerp(0,.18,focus)+lerp(0,-.12,retreat);bottle.position.y=lerp(-.15,.02,focus)+lerp(0,-.05,retreat);const scale=lerp(2.35,3.15,focus)*lerp(1,.94,retreat);bottle.scale.setScalar(scale);camera.position.z=lerp(6.7,5.15,focus)*lerp(1,1.18,retreat);camera.position.x=state.px*.045;camera.position.y=.15+state.py*.025;camera.lookAt(0,.05,0)}
 $('.scroll-progress span').style.height=`${p*100}%`;state.dirty=false;}
function frame(){if(state.raf)return;state.raf=requestAnimationFrame(()=>{state.raf=0;const diff=state.target-state.playhead;if(state.reduced)state.playhead=state.target;else state.playhead=Math.abs(diff)<.0005?state.target:state.playhead+diff*.105;const pdx=state.pointerX-state.px,pdy=state.pointerY-state.py;state.px+=pdx*(state.reduced?.3:.08);state.py+=pdy*(state.reduced?.3:.08);renderScene(state.playhead);if(Math.abs(diff)>.0005||Math.abs(pdx)>.001||Math.abs(pdy)>.001)frame()})}
function requestFrame(){frame()}
function wire(){addEventListener('scroll',setScrollTarget,{passive:true});addEventListener('resize',()=>{if(renderer){renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}requestFrame()},{passive:true});addEventListener('pointermove',e=>{if(matchMedia('(pointer:coarse)').matches)return;state.pointerX=clamp((e.clientX/innerWidth-.5)*2,-1,1);state.pointerY=clamp((e.clientY/innerHeight-.5)*2,-1,1);requestFrame()},{passive:true});
 document.querySelectorAll('[data-jump]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();const max=section.offsetHeight-innerHeight;const p=Number(a.dataset.jump);scrollTo({top:section.offsetTop+max*p,behavior:state.reduced?'auto':'smooth'})}));
 const rail=$('.rail'),cards=[...document.querySelectorAll('.card')],prev=$('.prev'),next=$('.next');let index=0,drag=false,startX=0,startScroll=0;
 function updateRail(animate=true){const gap=14,w=cards[0].getBoundingClientRect().width;rail.style.transition=animate?'transform .55s cubic-bezier(.2,.75,.2,1)':'none';rail.style.transform=`translate3d(${-index*(w+gap)}px,0,0)`;cards.forEach((c,i)=>c.classList.toggle('active',i===index));$('.rail-status').textContent=`0${index+1} / 03`}
 prev.onclick=()=>{index=Math.max(0,index-1);updateRail()};next.onclick=()=>{index=Math.min(cards.length-1,index+1);updateRail()};stage.addEventListener('pointerdown',e=>{if(!e.target.closest('.rail-viewport'))return;drag=true;startX=e.clientX;startScroll=index;rail.style.transition='none';rail.setPointerCapture?.(e.pointerId)});stage.addEventListener('pointermove',e=>{if(!drag)return;const w=cards[0].getBoundingClientRect().width+14;const d=(e.clientX-startX)/w;rail.style.transform=`translate3d(${-(startScroll-d)*(w)}px,0,0)`});stage.addEventListener('pointerup',e=>{if(!drag)return;drag=false;const d=e.clientX-startX;if(Math.abs(d)>50)index=clamp(startScroll+(d<0?1:-1),0,cards.length-1);updateRail()});addEventListener('keydown',e=>{if(e.key==='ArrowRight'){index=Math.min(2,index+1);updateRail()}if(e.key==='ArrowLeft'){index=Math.max(0,index-1);updateRail()}});
 $('.sound').addEventListener('click',e=>{const on=e.currentTarget.getAttribute('aria-pressed')!=='true';e.currentTarget.setAttribute('aria-pressed',on);e.currentTarget.querySelector('span').style.opacity=on?'1':'.35'});
}
setup3D();wire();setScrollTarget();requestFrame();
